spring.application.name=auth-service
# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/authdb
spring.datasource.username=root
spring.datasource.password=root

# Hibernate config cho MariaDB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


# JWT Configuration
jwt.secret=nuuxWfYz6+1ol8f0nOCuZD9zZ4LYD9PbIb7AON8/pegOAOZW8fQQ3LAzF7ojyozz0zFdAl+5JV3MziSUIsGftA==
jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thuhong05022003@gmail.com
spring.mail.password=dahlia523@@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Configuration
server.port=8080
